<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="0" hostname="MATT-PC" name="pytest" skipped="0" tests="44" time="0.972" timestamp="2019-09-27T23:48:40.710254"><testcase classname="core.test_config" file="core\test_config.py" line="3" name="test_when_init_then_config_object_returned" time="0.008"></testcase><testcase classname="core.test_helpers" file="core\test_helpers.py" line="4" name="test_when_makedirs_with_dir_path_and_not_exists_then_makedirs" time="0.001"></testcase><testcase classname="core.test_helpers" file="core\test_helpers.py" line="17" name="test_when_makedirs_with_file_path_and_not_exists_then_makedirs" time="0.003"></testcase><testcase classname="core.test_helpers" file="core\test_helpers.py" line="29" name="test_when_makedirs_with_dir_path_and_not_exists_then_not_makedirs" time="0.002"></testcase><testcase classname="core.test_helpers" file="core\test_helpers.py" line="41" name="test_when_makedirs_with_file_path_and_not_exists_then_not_makedirs" time="0.001"></testcase><testcase classname="core.test_helpers" file="core\test_helpers.py" line="54" name="test_when_find_all_files_and_full_path_and_recursive_then_full_path_files_returned" time="0.003"></testcase><testcase classname="core.test_helpers" file="core\test_helpers.py" line="65" name="test_when_find_all_files_and_not_full_path_and_not_recursive_then_full_path_files_returned" time="0.001"></testcase><testcase classname="core.test_pyfynance" file="core\test_pyfynance.py" line="17" name="test_when_init_the_pyfynance_object_returned" time="0.007"><system-err>2019-09-27 23:48:41,269 root                                INFO     Logging Service Initalised
2019-09-27 23:48:41,270 root                                INFO     PyFynance Version = 0.4
2019-09-27 23:48:41,270 root                                INFO     PyFynance Task Type = load_transactions
</system-err></testcase><testcase classname="core.test_pyfynance" file="core\test_pyfynance.py" line="27" name="test_when_run_and_task_is_successful_then_exit_code_zero" time="0.014"><system-err>2019-09-27 23:48:41,278 root                                INFO     Logging Service Initalised
2019-09-27 23:48:41,278 root                                INFO     Logging Service Initalised
2019-09-27 23:48:41,278 root                                INFO     PyFynance Version = 0.4
2019-09-27 23:48:41,278 root                                INFO     PyFynance Version = 0.4
2019-09-27 23:48:41,279 root                                INFO     PyFynance Task Type = load_transactions
2019-09-27 23:48:41,279 root                                INFO     PyFynance Task Type = load_transactions
2019-09-27 23:48:41,279 root                                INFO     Started PyFynance Application Run
2019-09-27 23:48:41,279 root                                INFO     Started PyFynance Application Run
2019-09-27 23:48:41,285 root                                INFO     PyFynance application ran successfully!  task_type = &apos;load_transactions&apos;
2019-09-27 23:48:41,285 root                                INFO     PyFynance application ran successfully!  task_type = &apos;load_transactions&apos;
2019-09-27 23:48:41,285 root                                INFO     Finished PyFynance Application Run
2019-09-27 23:48:41,285 root                                INFO     Finished PyFynance Application Run
</system-err></testcase><testcase classname="core.test_pyfynance" file="core\test_pyfynance.py" line="34" name="test_when_run_and_task_is_unsuccessful_then_exit_code_one" time="0.014"><system-err>2019-09-27 23:48:41,294 root                                INFO     Logging Service Initalised
2019-09-27 23:48:41,294 root                                INFO     Logging Service Initalised
2019-09-27 23:48:41,294 root                                INFO     Logging Service Initalised
2019-09-27 23:48:41,295 root                                INFO     PyFynance Version = 0.4
2019-09-27 23:48:41,295 root                                INFO     PyFynance Version = 0.4
2019-09-27 23:48:41,295 root                                INFO     PyFynance Version = 0.4
2019-09-27 23:48:41,295 root                                INFO     PyFynance Task Type = load_transactions
2019-09-27 23:48:41,295 root                                INFO     PyFynance Task Type = load_transactions
2019-09-27 23:48:41,295 root                                INFO     PyFynance Task Type = load_transactions
2019-09-27 23:48:41,296 root                                INFO     Started PyFynance Application Run
2019-09-27 23:48:41,296 root                                INFO     Started PyFynance Application Run
2019-09-27 23:48:41,296 root                                INFO     Started PyFynance Application Run
2019-09-27 23:48:41,301 root                                INFO     PyFynance application failed to run successfully :(  task_type = &apos;load_transactions&apos;
2019-09-27 23:48:41,301 root                                INFO     PyFynance application failed to run successfully :(  task_type = &apos;load_transactions&apos;
2019-09-27 23:48:41,301 root                                INFO     PyFynance application failed to run successfully :(  task_type = &apos;load_transactions&apos;
2019-09-27 23:48:41,302 root                                INFO     Finished PyFynance Application Run
2019-09-27 23:48:41,302 root                                INFO     Finished PyFynance Application Run
2019-09-27 23:48:41,302 root                                INFO     Finished PyFynance Application Run
</system-err></testcase><testcase classname="core.test_pyfynance" file="core\test_pyfynance.py" line="41" name="test_when_run_and_error_then_error_raised" time="0.009"><system-err>2019-09-27 23:48:41,310 root                                INFO     Logging Service Initalised
2019-09-27 23:48:41,310 root                                INFO     Logging Service Initalised
2019-09-27 23:48:41,310 root                                INFO     Logging Service Initalised
2019-09-27 23:48:41,310 root                                INFO     Logging Service Initalised
2019-09-27 23:48:41,311 root                                INFO     PyFynance Version = 0.4
2019-09-27 23:48:41,311 root                                INFO     PyFynance Version = 0.4
2019-09-27 23:48:41,311 root                                INFO     PyFynance Version = 0.4
2019-09-27 23:48:41,311 root                                INFO     PyFynance Version = 0.4
2019-09-27 23:48:41,312 root                                INFO     PyFynance Task Type = load_transactions
2019-09-27 23:48:41,312 root                                INFO     PyFynance Task Type = load_transactions
2019-09-27 23:48:41,312 root                                INFO     PyFynance Task Type = load_transactions
2019-09-27 23:48:41,312 root                                INFO     PyFynance Task Type = load_transactions
2019-09-27 23:48:41,312 root                                INFO     Started PyFynance Application Run
2019-09-27 23:48:41,312 root                                INFO     Started PyFynance Application Run
2019-09-27 23:48:41,312 root                                INFO     Started PyFynance Application Run
2019-09-27 23:48:41,312 root                                INFO     Started PyFynance Application Run
2019-09-27 23:48:41,313 root                                ERROR    PyFynance experienced a fatal exception while running task of task_type &apos;load_transactions&apos;.  exception = &apos;thrown_error_message&apos;
Traceback (most recent call last):
  File &quot;D:\git-repos\PyFynance\PyFynance\core\pyfynance.py&quot;, line 33, in run
    passed = self._execute_tasks()
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1092, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1147, in _mock_call
    raise result
Exception: thrown_error_message
2019-09-27 23:48:41,313 root                                ERROR    PyFynance experienced a fatal exception while running task of task_type &apos;load_transactions&apos;.  exception = &apos;thrown_error_message&apos;
Traceback (most recent call last):
  File &quot;D:\git-repos\PyFynance\PyFynance\core\pyfynance.py&quot;, line 33, in run
    passed = self._execute_tasks()
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1092, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1147, in _mock_call
    raise result
Exception: thrown_error_message
2019-09-27 23:48:41,313 root                                ERROR    PyFynance experienced a fatal exception while running task of task_type &apos;load_transactions&apos;.  exception = &apos;thrown_error_message&apos;
Traceback (most recent call last):
  File &quot;D:\git-repos\PyFynance\PyFynance\core\pyfynance.py&quot;, line 33, in run
    passed = self._execute_tasks()
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1092, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1147, in _mock_call
    raise result
Exception: thrown_error_message
2019-09-27 23:48:41,313 root                                ERROR    PyFynance experienced a fatal exception while running task of task_type &apos;load_transactions&apos;.  exception = &apos;thrown_error_message&apos;
Traceback (most recent call last):
  File &quot;D:\git-repos\PyFynance\PyFynance\core\pyfynance.py&quot;, line 33, in run
    passed = self._execute_tasks()
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1092, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1147, in _mock_call
    raise result
Exception: thrown_error_message
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="44" name="test_when_init_then_database_service_returned" time="0.004"></testcase><testcase classname="services.test_database" file="services\test_database.py" line="64" name="test_when_start_db_and_current_and_good_db_name_then_db_started" time="0.008"><system-err>2019-09-27 23:48:41,333 services.database                   INFO     Attempting to start the database service for database &apos;transactions&apos;
2019-09-27 23:48:41,333 services.database                   INFO     Attempting to start the database service for database &apos;transactions&apos;
2019-09-27 23:48:41,333 services.database                   INFO     Attempting to start the database service for database &apos;transactions&apos;
2019-09-27 23:48:41,333 services.database                   INFO     Attempting to start the database service for database &apos;transactions&apos;
2019-09-27 23:48:41,334 services.database                   DEBUG    Attempting to execute sql command &apos;CREATE TABLE IF NOT EXISTS transactions (institution text, account text, tran_id text, tran_type text, amount decimal, narrative text, date_posted text, PRIMARY KEY (institution, account, tran_id));&apos;
2019-09-27 23:48:41,334 services.database                   DEBUG    Attempting to execute sql command &apos;CREATE TABLE IF NOT EXISTS transactions (institution text, account text, tran_id text, tran_type text, amount decimal, narrative text, date_posted text, PRIMARY KEY (institution, account, tran_id));&apos;
2019-09-27 23:48:41,334 services.database                   DEBUG    Attempting to execute sql command &apos;CREATE TABLE IF NOT EXISTS transactions (institution text, account text, tran_id text, tran_type text, amount decimal, narrative text, date_posted text, PRIMARY KEY (institution, account, tran_id));&apos;
2019-09-27 23:48:41,334 services.database                   DEBUG    Attempting to execute sql command &apos;CREATE TABLE IF NOT EXISTS transactions (institution text, account text, tran_id text, tran_type text, amount decimal, narrative text, date_posted text, PRIMARY KEY (institution, account, tran_id));&apos;
2019-09-27 23:48:41,335 services.database                   DEBUG    Successful execution of sql command &apos;CREATE TABLE IF NOT EXISTS transactions (institution text, account text, tran_id text, tran_type text, amount decimal, narrative text, date_posted text, PRIMARY KEY (institution, account, tran_id));&apos;
2019-09-27 23:48:41,335 services.database                   DEBUG    Successful execution of sql command &apos;CREATE TABLE IF NOT EXISTS transactions (institution text, account text, tran_id text, tran_type text, amount decimal, narrative text, date_posted text, PRIMARY KEY (institution, account, tran_id));&apos;
2019-09-27 23:48:41,335 services.database                   DEBUG    Successful execution of sql command &apos;CREATE TABLE IF NOT EXISTS transactions (institution text, account text, tran_id text, tran_type text, amount decimal, narrative text, date_posted text, PRIMARY KEY (institution, account, tran_id));&apos;
2019-09-27 23:48:41,335 services.database                   DEBUG    Successful execution of sql command &apos;CREATE TABLE IF NOT EXISTS transactions (institution text, account text, tran_id text, tran_type text, amount decimal, narrative text, date_posted text, PRIMARY KEY (institution, account, tran_id));&apos;
2019-09-27 23:48:41,335 services.database                   INFO     Successfully started the database service for database &apos;transactions&apos;
2019-09-27 23:48:41,335 services.database                   INFO     Successfully started the database service for database &apos;transactions&apos;
2019-09-27 23:48:41,335 services.database                   INFO     Successfully started the database service for database &apos;transactions&apos;
2019-09-27 23:48:41,335 services.database                   INFO     Successfully started the database service for database &apos;transactions&apos;
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="79" name="test_when_start_db_and_backup_and_good_db_name_then_db_started" time="0.006"><system-err>2019-09-27 23:48:41,350 services.database                   INFO     Attempting to start the database service for database &apos;transactions&apos;
2019-09-27 23:48:41,350 services.database                   INFO     Attempting to start the database service for database &apos;transactions&apos;
2019-09-27 23:48:41,350 services.database                   INFO     Attempting to start the database service for database &apos;transactions&apos;
2019-09-27 23:48:41,350 services.database                   INFO     Attempting to start the database service for database &apos;transactions&apos;
2019-09-27 23:48:41,351 services.database                   INFO     Successfully started the database service for database &apos;transactions&apos;
2019-09-27 23:48:41,351 services.database                   INFO     Successfully started the database service for database &apos;transactions&apos;
2019-09-27 23:48:41,351 services.database                   INFO     Successfully started the database service for database &apos;transactions&apos;
2019-09-27 23:48:41,351 services.database                   INFO     Successfully started the database service for database &apos;transactions&apos;
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="95" name="test_when_start_db_and_bad_db_name_then_error" time="0.004"><system-err>2019-09-27 23:48:41,358 services.database                   INFO     Attempting to start the database service for database &apos;not_a_real_db&apos;
2019-09-27 23:48:41,358 services.database                   INFO     Attempting to start the database service for database &apos;not_a_real_db&apos;
2019-09-27 23:48:41,358 services.database                   INFO     Attempting to start the database service for database &apos;not_a_real_db&apos;
2019-09-27 23:48:41,358 services.database                   INFO     Attempting to start the database service for database &apos;not_a_real_db&apos;
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="103" name="test_when_stop_db_and_commit_and_good_db_name_then_db_stopped" time="0.007"><system-err>2019-09-27 23:48:41,367 services.database                   INFO     Attempting to stop the database service for database &apos;transactions&apos; with commit set to True
2019-09-27 23:48:41,367 services.database                   INFO     Attempting to stop the database service for database &apos;transactions&apos; with commit set to True
2019-09-27 23:48:41,367 services.database                   INFO     Attempting to stop the database service for database &apos;transactions&apos; with commit set to True
2019-09-27 23:48:41,367 services.database                   INFO     Attempting to stop the database service for database &apos;transactions&apos; with commit set to True
2019-09-27 23:48:41,369 services.database                   INFO     Successfully stopped the database service for database &apos;transactions&apos; with commit set to True
2019-09-27 23:48:41,369 services.database                   INFO     Successfully stopped the database service for database &apos;transactions&apos; with commit set to True
2019-09-27 23:48:41,369 services.database                   INFO     Successfully stopped the database service for database &apos;transactions&apos; with commit set to True
2019-09-27 23:48:41,369 services.database                   INFO     Successfully stopped the database service for database &apos;transactions&apos; with commit set to True
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="114" name="test_when_stop_db_and_no_commit_and_good_db_name_then_db_stopped" time="0.008"><system-err>2019-09-27 23:48:41,378 services.database                   INFO     Attempting to stop the database service for database &apos;transactions&apos; with commit set to False
2019-09-27 23:48:41,378 services.database                   INFO     Attempting to stop the database service for database &apos;transactions&apos; with commit set to False
2019-09-27 23:48:41,378 services.database                   INFO     Attempting to stop the database service for database &apos;transactions&apos; with commit set to False
2019-09-27 23:48:41,378 services.database                   INFO     Attempting to stop the database service for database &apos;transactions&apos; with commit set to False
2019-09-27 23:48:41,379 services.database                   INFO     Successfully stopped the database service for database &apos;transactions&apos; with commit set to False
2019-09-27 23:48:41,379 services.database                   INFO     Successfully stopped the database service for database &apos;transactions&apos; with commit set to False
2019-09-27 23:48:41,379 services.database                   INFO     Successfully stopped the database service for database &apos;transactions&apos; with commit set to False
2019-09-27 23:48:41,379 services.database                   INFO     Successfully stopped the database service for database &apos;transactions&apos; with commit set to False
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="123" name="test_when_stop_db_and_bad_db_name_then_error" time="0.005"><system-err>2019-09-27 23:48:41,386 services.database                   INFO     Attempting to stop the database service for database &apos;not_a_real_db&apos; with commit set to True
2019-09-27 23:48:41,386 services.database                   INFO     Attempting to stop the database service for database &apos;not_a_real_db&apos; with commit set to True
2019-09-27 23:48:41,386 services.database                   INFO     Attempting to stop the database service for database &apos;not_a_real_db&apos; with commit set to True
2019-09-27 23:48:41,386 services.database                   INFO     Attempting to stop the database service for database &apos;not_a_real_db&apos; with commit set to True
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="131" name="test_when_insert_and_db_good_and_table_good_then_sql_called" time="0.008"><system-err>2019-09-27 23:48:41,394 services.database                   INFO     Attempting insert of data into &apos;transactions.transactions&apos;
2019-09-27 23:48:41,394 services.database                   INFO     Attempting insert of data into &apos;transactions.transactions&apos;
2019-09-27 23:48:41,394 services.database                   INFO     Attempting insert of data into &apos;transactions.transactions&apos;
2019-09-27 23:48:41,394 services.database                   INFO     Attempting insert of data into &apos;transactions.transactions&apos;
2019-09-27 23:48:41,395 services.database                   DEBUG    Attempting to execute sql command &apos;INSERT INTO transactions(institution, account, tran_id, tran_type, amount, narrative, date_posted) VALUES(&quot;matts_fully_sick_bank&quot;, &quot;multi-billion_dollar_savings&quot;, &quot;42069&quot;, &quot;CREDIT&quot;, -135000.00, &quot;sweet ass tesla&quot;, &quot;20600707103000&quot;);&apos;
2019-09-27 23:48:41,395 services.database                   DEBUG    Attempting to execute sql command &apos;INSERT INTO transactions(institution, account, tran_id, tran_type, amount, narrative, date_posted) VALUES(&quot;matts_fully_sick_bank&quot;, &quot;multi-billion_dollar_savings&quot;, &quot;42069&quot;, &quot;CREDIT&quot;, -135000.00, &quot;sweet ass tesla&quot;, &quot;20600707103000&quot;);&apos;
2019-09-27 23:48:41,395 services.database                   DEBUG    Attempting to execute sql command &apos;INSERT INTO transactions(institution, account, tran_id, tran_type, amount, narrative, date_posted) VALUES(&quot;matts_fully_sick_bank&quot;, &quot;multi-billion_dollar_savings&quot;, &quot;42069&quot;, &quot;CREDIT&quot;, -135000.00, &quot;sweet ass tesla&quot;, &quot;20600707103000&quot;);&apos;
2019-09-27 23:48:41,395 services.database                   DEBUG    Attempting to execute sql command &apos;INSERT INTO transactions(institution, account, tran_id, tran_type, amount, narrative, date_posted) VALUES(&quot;matts_fully_sick_bank&quot;, &quot;multi-billion_dollar_savings&quot;, &quot;42069&quot;, &quot;CREDIT&quot;, -135000.00, &quot;sweet ass tesla&quot;, &quot;20600707103000&quot;);&apos;
2019-09-27 23:48:41,397 services.database                   DEBUG    Successful execution of sql command &apos;INSERT INTO transactions(institution, account, tran_id, tran_type, amount, narrative, date_posted) VALUES(&quot;matts_fully_sick_bank&quot;, &quot;multi-billion_dollar_savings&quot;, &quot;42069&quot;, &quot;CREDIT&quot;, -135000.00, &quot;sweet ass tesla&quot;, &quot;20600707103000&quot;);&apos;
2019-09-27 23:48:41,397 services.database                   DEBUG    Successful execution of sql command &apos;INSERT INTO transactions(institution, account, tran_id, tran_type, amount, narrative, date_posted) VALUES(&quot;matts_fully_sick_bank&quot;, &quot;multi-billion_dollar_savings&quot;, &quot;42069&quot;, &quot;CREDIT&quot;, -135000.00, &quot;sweet ass tesla&quot;, &quot;20600707103000&quot;);&apos;
2019-09-27 23:48:41,397 services.database                   DEBUG    Successful execution of sql command &apos;INSERT INTO transactions(institution, account, tran_id, tran_type, amount, narrative, date_posted) VALUES(&quot;matts_fully_sick_bank&quot;, &quot;multi-billion_dollar_savings&quot;, &quot;42069&quot;, &quot;CREDIT&quot;, -135000.00, &quot;sweet ass tesla&quot;, &quot;20600707103000&quot;);&apos;
2019-09-27 23:48:41,397 services.database                   DEBUG    Successful execution of sql command &apos;INSERT INTO transactions(institution, account, tran_id, tran_type, amount, narrative, date_posted) VALUES(&quot;matts_fully_sick_bank&quot;, &quot;multi-billion_dollar_savings&quot;, &quot;42069&quot;, &quot;CREDIT&quot;, -135000.00, &quot;sweet ass tesla&quot;, &quot;20600707103000&quot;);&apos;
2019-09-27 23:48:41,397 services.database                   INFO     Successful insert of data into &apos;transactions.transactions&apos;
2019-09-27 23:48:41,397 services.database                   INFO     Successful insert of data into &apos;transactions.transactions&apos;
2019-09-27 23:48:41,397 services.database                   INFO     Successful insert of data into &apos;transactions.transactions&apos;
2019-09-27 23:48:41,397 services.database                   INFO     Successful insert of data into &apos;transactions.transactions&apos;
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="141" name="test_when_insert_and_bad_db_name_then_error" time="0.005"><system-err>2019-09-27 23:48:41,406 services.database                   INFO     Attempting insert of data into &apos;not_a_real_db.transactions&apos;
2019-09-27 23:48:41,406 services.database                   INFO     Attempting insert of data into &apos;not_a_real_db.transactions&apos;
2019-09-27 23:48:41,406 services.database                   INFO     Attempting insert of data into &apos;not_a_real_db.transactions&apos;
2019-09-27 23:48:41,406 services.database                   INFO     Attempting insert of data into &apos;not_a_real_db.transactions&apos;
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="149" name="test_when_insert_and_bad_table_name_then_error" time="0.005"><system-err>2019-09-27 23:48:41,414 services.database                   INFO     Attempting insert of data into &apos;transactions.not_a_real_db&apos;
2019-09-27 23:48:41,414 services.database                   INFO     Attempting insert of data into &apos;transactions.not_a_real_db&apos;
2019-09-27 23:48:41,414 services.database                   INFO     Attempting insert of data into &apos;transactions.not_a_real_db&apos;
2019-09-27 23:48:41,414 services.database                   INFO     Attempting insert of data into &apos;transactions.not_a_real_db&apos;
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="157" name="test_when_select_and_columns_none_and_where_none_then_sql_executed" time="0.008"><system-err>2019-09-27 23:48:41,421 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,421 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,421 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,421 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,422 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT * FROM transactions;&apos;
2019-09-27 23:48:41,422 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT * FROM transactions;&apos;
2019-09-27 23:48:41,422 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT * FROM transactions;&apos;
2019-09-27 23:48:41,422 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT * FROM transactions;&apos;
2019-09-27 23:48:41,423 services.database                   DEBUG    Successful execution of sql command &apos;SELECT * FROM transactions;&apos;
2019-09-27 23:48:41,423 services.database                   DEBUG    Successful execution of sql command &apos;SELECT * FROM transactions;&apos;
2019-09-27 23:48:41,423 services.database                   DEBUG    Successful execution of sql command &apos;SELECT * FROM transactions;&apos;
2019-09-27 23:48:41,423 services.database                   DEBUG    Successful execution of sql command &apos;SELECT * FROM transactions;&apos;
2019-09-27 23:48:41,424 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,424 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,424 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,424 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="166" name="test_when_select_and_columns_defined_and_where_none_then_sql_executed" time="0.008"><system-err>2019-09-27 23:48:41,433 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,433 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,433 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,433 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,434 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT name, yeet-ness FROM transactions;&apos;
2019-09-27 23:48:41,434 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT name, yeet-ness FROM transactions;&apos;
2019-09-27 23:48:41,434 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT name, yeet-ness FROM transactions;&apos;
2019-09-27 23:48:41,434 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT name, yeet-ness FROM transactions;&apos;
2019-09-27 23:48:41,435 services.database                   DEBUG    Successful execution of sql command &apos;SELECT name, yeet-ness FROM transactions;&apos;
2019-09-27 23:48:41,435 services.database                   DEBUG    Successful execution of sql command &apos;SELECT name, yeet-ness FROM transactions;&apos;
2019-09-27 23:48:41,435 services.database                   DEBUG    Successful execution of sql command &apos;SELECT name, yeet-ness FROM transactions;&apos;
2019-09-27 23:48:41,435 services.database                   DEBUG    Successful execution of sql command &apos;SELECT name, yeet-ness FROM transactions;&apos;
2019-09-27 23:48:41,436 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,436 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,436 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,436 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="176" name="test_when_select_and_columns_none_and_where_defined_then_sql_executed" time="0.011"><system-err>2019-09-27 23:48:41,446 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,446 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,446 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,446 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,446 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT * FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,446 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT * FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,446 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT * FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,446 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT * FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,448 services.database                   DEBUG    Successful execution of sql command &apos;SELECT * FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,448 services.database                   DEBUG    Successful execution of sql command &apos;SELECT * FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,448 services.database                   DEBUG    Successful execution of sql command &apos;SELECT * FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,448 services.database                   DEBUG    Successful execution of sql command &apos;SELECT * FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,449 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,449 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,449 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,449 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="186" name="test_when_select_and_columns_defined_and_where_defined_then_sql_executed" time="0.009"><system-err>2019-09-27 23:48:41,462 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,462 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,462 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,462 services.database                   INFO     Attempting select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,462 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT name, yeet-ness FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,462 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT name, yeet-ness FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,462 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT name, yeet-ness FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,462 services.database                   DEBUG    Attempting to execute sql command &apos;SELECT name, yeet-ness FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,463 services.database                   DEBUG    Successful execution of sql command &apos;SELECT name, yeet-ness FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,463 services.database                   DEBUG    Successful execution of sql command &apos;SELECT name, yeet-ness FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,463 services.database                   DEBUG    Successful execution of sql command &apos;SELECT name, yeet-ness FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,463 services.database                   DEBUG    Successful execution of sql command &apos;SELECT name, yeet-ness FROM transactions WHERE power_level &gt; 9000;&apos;
2019-09-27 23:48:41,463 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,463 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,463 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
2019-09-27 23:48:41,463 services.database                   INFO     Successful select of data from &apos;transactions.transactions&apos;
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="197" name="test_when_select_and_bad_db_name_then_error" time="0.005"><system-err>2019-09-27 23:48:41,471 services.database                   INFO     Attempting select of data from &apos;not_a_real_db.transactions&apos;
2019-09-27 23:48:41,471 services.database                   INFO     Attempting select of data from &apos;not_a_real_db.transactions&apos;
2019-09-27 23:48:41,471 services.database                   INFO     Attempting select of data from &apos;not_a_real_db.transactions&apos;
2019-09-27 23:48:41,471 services.database                   INFO     Attempting select of data from &apos;not_a_real_db.transactions&apos;
</system-err></testcase><testcase classname="services.test_database" file="services\test_database.py" line="205" name="test_when_select_and_bad_table_name_then_error" time="0.004"><system-err>2019-09-27 23:48:41,479 services.database                   INFO     Attempting select of data from &apos;transactions.not_a_real_db&apos;
2019-09-27 23:48:41,479 services.database                   INFO     Attempting select of data from &apos;transactions.not_a_real_db&apos;
2019-09-27 23:48:41,479 services.database                   INFO     Attempting select of data from &apos;transactions.not_a_real_db&apos;
2019-09-27 23:48:41,479 services.database                   INFO     Attempting select of data from &apos;transactions.not_a_real_db&apos;
</system-err></testcase><testcase classname="services.test_ofx_parser" file="services\test_ofx_parser.py" line="49" name="test_when_init_then_ofx_parser_returned" time="0.001"></testcase><testcase classname="services.test_ofx_parser" file="services\test_ofx_parser.py" line="56" name="test_when_parse_and_banking_transactions_then_return_transations" time="0.026"></testcase><testcase classname="services.test_ofx_parser" file="services\test_ofx_parser.py" line="74" name="test_when_parse_and_bad_object_type_then_raise_error" time="0.004"></testcase><testcase classname="services.test_ofx_parser" file="services\test_ofx_parser.py" line="81" name="test_when_parse_and_file_path_not_a_file_then_raise_error" time="0.006"></testcase><testcase classname="services.test_ofx_parser" file="services\test_ofx_parser.py" line="88" name="test_when_parse_and_file_not_ofx_or_qfx_then_raise_error" time="0.005"></testcase><testcase classname="tasks.test_task_base" file="tasks\test_task_base.py" line="19" name="test_when_init_the_base_task_returned" time="0.009"></testcase><testcase classname="tasks.test_task_base" file="tasks\test_task_base.py" line="25" name="test_when_execute_and_successful_then_true_returned" time="0.007"><system-err>2019-09-27 23:48:41,551 tasks.task_base                     INFO     Beginning task execution for task type &apos;BaseTask&apos;
2019-09-27 23:48:41,551 tasks.task_base                     INFO     Beginning task execution for task type &apos;BaseTask&apos;
2019-09-27 23:48:41,551 tasks.task_base                     INFO     Beginning task execution for task type &apos;BaseTask&apos;
2019-09-27 23:48:41,551 tasks.task_base                     INFO     Beginning task execution for task type &apos;BaseTask&apos;
2019-09-27 23:48:41,552 tasks.task_base                     INFO     Finished task execution for task type &apos;BaseTask&apos; with status &apos;Success&apos;
2019-09-27 23:48:41,552 tasks.task_base                     INFO     Finished task execution for task type &apos;BaseTask&apos; with status &apos;Success&apos;
2019-09-27 23:48:41,552 tasks.task_base                     INFO     Finished task execution for task type &apos;BaseTask&apos; with status &apos;Success&apos;
2019-09-27 23:48:41,552 tasks.task_base                     INFO     Finished task execution for task type &apos;BaseTask&apos; with status &apos;Success&apos;
</system-err></testcase><testcase classname="tasks.test_task_base" file="tasks\test_task_base.py" line="31" name="test_when_execute_and_unsuccessful_then_true_returned" time="0.009"><system-err>2019-09-27 23:48:41,562 tasks.task_base                     INFO     Beginning task execution for task type &apos;BaseTask&apos;
2019-09-27 23:48:41,562 tasks.task_base                     INFO     Beginning task execution for task type &apos;BaseTask&apos;
2019-09-27 23:48:41,562 tasks.task_base                     INFO     Beginning task execution for task type &apos;BaseTask&apos;
2019-09-27 23:48:41,562 tasks.task_base                     INFO     Beginning task execution for task type &apos;BaseTask&apos;
2019-09-27 23:48:41,562 tasks.task_base                     ERROR    PyFynance encountered an error while running task.  task_error_message
Traceback (most recent call last):
  File &quot;D:\git-repos\PyFynance\PyFynance\tasks\task_base.py&quot;, line 62, in execute
    self.do_task()
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1092, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1147, in _mock_call
    raise result
core.exceptions.TaskError: task_error_message
2019-09-27 23:48:41,562 tasks.task_base                     ERROR    PyFynance encountered an error while running task.  task_error_message
Traceback (most recent call last):
  File &quot;D:\git-repos\PyFynance\PyFynance\tasks\task_base.py&quot;, line 62, in execute
    self.do_task()
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1092, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1147, in _mock_call
    raise result
core.exceptions.TaskError: task_error_message
2019-09-27 23:48:41,562 tasks.task_base                     ERROR    PyFynance encountered an error while running task.  task_error_message
Traceback (most recent call last):
  File &quot;D:\git-repos\PyFynance\PyFynance\tasks\task_base.py&quot;, line 62, in execute
    self.do_task()
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1092, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1147, in _mock_call
    raise result
core.exceptions.TaskError: task_error_message
2019-09-27 23:48:41,562 tasks.task_base                     ERROR    PyFynance encountered an error while running task.  task_error_message
Traceback (most recent call last):
  File &quot;D:\git-repos\PyFynance\PyFynance\tasks\task_base.py&quot;, line 62, in execute
    self.do_task()
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1092, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File &quot;C:\Users\Matt\.virtualenvs\PyFynance-faJQoYoX\lib\site-packages\mock\mock.py&quot;, line 1147, in _mock_call
    raise result
core.exceptions.TaskError: task_error_message
2019-09-27 23:48:41,564 tasks.task_base                     INFO     Finished task execution for task type &apos;BaseTask&apos; with status &apos;Failure&apos;
2019-09-27 23:48:41,564 tasks.task_base                     INFO     Finished task execution for task type &apos;BaseTask&apos; with status &apos;Failure&apos;
2019-09-27 23:48:41,564 tasks.task_base                     INFO     Finished task execution for task type &apos;BaseTask&apos; with status &apos;Failure&apos;
2019-09-27 23:48:41,564 tasks.task_base                     INFO     Finished task execution for task type &apos;BaseTask&apos; with status &apos;Failure&apos;
</system-err></testcase><testcase classname="tasks.test_task_base" file="tasks\test_task_base.py" line="38" name="test_when_get_args_repr_then_correct_string_returned" time="0.008"></testcase><testcase classname="tasks.test_task_load_transactions" file="tasks\test_task_load_transactions.py" line="100" name="test_when_init_the_correct_object_returned" time="0.007"></testcase><testcase classname="tasks.test_task_load_transactions" file="tasks\test_task_load_transactions.py" line="111" name="test_when_repr_then_correct_str_returned" time="0.005"></testcase><testcase classname="tasks.test_task_load_transactions" file="tasks\test_task_load_transactions.py" line="116" name="test_when_before_task_then_correct_methods_called" time="0.008"><system-err>2019-09-27 23:48:41,603 tasks.task_base                     INFO     Beginning before_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,603 tasks.task_base                     INFO     Beginning before_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,603 tasks.task_base                     INFO     Beginning before_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,603 tasks.task_base                     INFO     Beginning before_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,604 tasks.task_base                     INFO     Finished before_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,604 tasks.task_base                     INFO     Finished before_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,604 tasks.task_base                     INFO     Finished before_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,604 tasks.task_base                     INFO     Finished before_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
</system-err></testcase><testcase classname="tasks.test_task_load_transactions" file="tasks\test_task_load_transactions.py" line="122" name="test_when_do_task_and_no_trans_in_db_then_load_correct_trans" time="0.011"><system-err>2019-09-27 23:48:41,618 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,618 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,618 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,618 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,619 tasks.task_base                     INFO     Finished do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,619 tasks.task_base                     INFO     Finished do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,619 tasks.task_base                     INFO     Finished do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,619 tasks.task_base                     INFO     Finished do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
</system-err></testcase><testcase classname="tasks.test_task_load_transactions" file="tasks\test_task_load_transactions.py" line="139" name="test_when_do_task_and_some_trans_in_db_then_load_correct_trans" time="0.011"><system-err>2019-09-27 23:48:41,633 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,633 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,633 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,633 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,635 tasks.task_base                     INFO     Finished do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,635 tasks.task_base                     INFO     Finished do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,635 tasks.task_base                     INFO     Finished do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,635 tasks.task_base                     INFO     Finished do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
</system-err></testcase><testcase classname="tasks.test_task_load_transactions" file="tasks\test_task_load_transactions.py" line="156" name="test_when_do_task_and_all_trans_in_db_then_load_no_trans" time="0.013"><system-err>2019-09-27 23:48:41,650 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,650 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,650 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,650 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,651 tasks.task_base                     INFO     Finished do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,651 tasks.task_base                     INFO     Finished do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,651 tasks.task_base                     INFO     Finished do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,651 tasks.task_base                     INFO     Finished do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
</system-err></testcase><testcase classname="tasks.test_task_load_transactions" file="tasks\test_task_load_transactions.py" line="173" name="test_when_do_task_and_tran_no_name_memo_then_raise_error" time="0.011"><system-err>2019-09-27 23:48:41,665 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,665 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,665 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,665 tasks.task_base                     INFO     Beginning do_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
</system-err></testcase><testcase classname="tasks.test_task_load_transactions" file="tasks\test_task_load_transactions.py" line="190" name="test_when_after_task_then_correct_methods_called" time="0.009"><system-err>2019-09-27 23:48:41,676 tasks.task_base                     INFO     Beginning after_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,676 tasks.task_base                     INFO     Beginning after_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,676 tasks.task_base                     INFO     Beginning after_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,676 tasks.task_base                     INFO     Beginning after_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,677 tasks.task_base                     INFO     Finished after_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,677 tasks.task_base                     INFO     Finished after_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,677 tasks.task_base                     INFO     Finished after_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
2019-09-27 23:48:41,677 tasks.task_base                     INFO     Finished after_task method of task &apos;PyFynance.Tasks.LoadTransactionsTask(task_type=load_transactions, institution=MyBank, account=CreditCard, runtime=2015-02-14 10:11:12)&apos;.
</system-err></testcase></testsuite></testsuites>